### ISSUE TITLE
ListClassifier: List element was misordered and did not start new list. Expected 1

### ISSUE THREAD

**Issue by sebastianmng** [MartinPaulEve/meTypeset#89]
Hello @MartinPaulEve ,

I'm running `meTypeset.py docx directory/file.docx try015  --noimageprocessing --debug` on a Mac OSX Yosemite. The List Classifier method process_number_list is not catching the numbering in the docx after track changes. So where the docx has numbering 1-9 with track changes correcting <del>10</del>6,  process_number_list  sees 106 and returns "List element was misordered and did not start new list. Expected 1." As a result the TEI  output for the back element contains a list and a series of p nodes while the NLM output has entirely lost the list and retains only the p nodes.

I'm guessing the solution will lie in how meTypeset handles track changes. Any ideas on how to troubleshoot this issue would be great. I can provide the entire debug output if needed. Thanks.

**Comment by MartinPaulEve** [comment]
Hi @sebastianmng,

Thanks for this. Would you be able to drop me an email with the smallest docx file that you can create that will replicate this bug? I can then create a test case and try to fix it.

Best wishes,

Martin

**Comment by sebastianmng** [comment]
I've sent a toy docx that reproduces the issue to your bbk account, thank you @MartinPaulEve !

**Comment by MartinPaulEve** [comment]
Hi @sebastianmng,

I've just been looking at the test document that you sent me and can see that there's actually two problems, both of which need fixing.

1. The numeric list classifier should not run in sections where it has identified that it's working on a bibliography.

2. I think the best solution to the track changes problem is to identify changed elements and to accept the changed content. This is easy to do in LibreOffice but hard to do in meTypeset at the moment. The relevant portion of the OOXML spec is 17.13.5 and there are 37 tags that can have changed content type.

All in all, I feel confident that the first part can be fixed. We should just exclude the listclassifier from running inside a reference list. This can also be temporarily fixed by changing the aggression level to 4 and modifying settings.xml so that numberlist classifier is not run.

I don't feel confident about fixing edits that are stored but not accepted. The document parsing here is well beyond any time level that I can commit here in the near future.

Thoughts welcome!

**Comment by sebastianmng** [comment]
Thank you @MartinPaulEve ! I'll start working on 1. I believe 2 can be solved with user documentation, but will discuss further with the rest of the team.

**Comment by axfelix** [comment]
Any chance either of you still have the toy document referenced above? Trying to update the tests to merge in Sebastian's fixes.

**Comment by axfelix** [comment]
Additionally, @sebastianmng, is https://github.com/sebastianmng/meTypeset/commit/9a8d48ab6b609d334d02bd38d3d202e44e507f36 also a part of this same fix? I can't find any documentation in our Slack or the issue tracker of what that commit would be fixing independently.

**Comment by sebastianmng** [comment]
Yes, that is thecase @axfelix

**Comment by axfelix** [comment]
OK, great, then all I need is the toy document referenced above to finally finish a comprehensive set of tests for your fixes to get them merged.

Hopeful you still have it in email archives somewhere, or can recreate it.

**Comment by sebastianmng** [comment]
Ok, sent!  @axfelix
